"""Added Cart table

Revision ID: c75b752a5ceb
Revises: a1dfbe5bbf43
Create Date: 2024-07-07 19:05:10.258187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75b752a5ceb'
down_revision: Union[str, None] = 'a1dfbe5bbf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
