"""added name to Address

Revision ID: 5af4ae9c8b7b
Revises: cc8881d74d74
Create Date: 2024-09-24 19:29:23.373135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af4ae9c8b7b'
down_revision: Union[str, None] = 'cc8881d74d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'name')
    # ### end Alembic commands ###
